In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('new_uber.csv')

In [3]:
df1=pd.read_csv('uber_dataset.csv')

In [4]:
df1.shape

(322844, 57)

In [5]:
x=df[['source','destination','cab_type','name']]

In [6]:
y=df1['price']

In [7]:
from sklearn.model_selection import train_test_split

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [10]:
from sklearn.ensemble import RandomForestRegressor 

In [11]:
random = RandomForestRegressor(n_estimators = 100, random_state = 0) 
random.fit(x_train , y_train)  
random.score(x_test, y_test)

0.9524653820717268

In [13]:
predictions = random.predict(x_test)

In [14]:
predictions

array([10.8782155 , 10.        ,  4.18855567, ..., 32.96643104,
       29.81578233, 10.        ])

In [64]:
df.isna().sum()

month                     0
source                    0
destination               0
cab_type                  0
product_id                0
name                      0
surge_multiplier          0
temperature               0
icon                      0
temperatureMin            0
apparentTemperatureMin    0
dtype: int64

In [15]:
df.head()

month  source  destination  cab_type  product_id  name  surge_multiplier  \
0      1       5            7         0           4     2                 0   
1      0       5            7         0           5     1                 0   
2      1       0            8         0           4     2                 0   
3      0       0            8         0           5     1                 0   
4      1       6           11         1           0     5                 0   

   temperature  icon  temperatureMin  apparentTemperatureMin  
0        42.34     5           39.89                   33.73  
1        43.58     6           40.49                   36.20  
2        45.58     3           43.09                   39.90  
3        40.13     0           28.64                   29.29  
4        32.85     4           18.29                   13.79

In [39]:
random.predict(a)

C:\Users\ashut\anaconda3\Conda\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([5.169673])

In [17]:
x_train.shape

(258275, 4)

In [18]:
from sklearn.linear_model import LinearRegression

In [19]:
linear = LinearRegression()
linear.fit(x_train, y_train)
linear.score(x_test, y_test)

0.7205585533318128

In [21]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score
cv=ShuffleSplit(n_splits=5,test_size=0.2,random_state=0)
cross_val_score(LinearRegression(),x_test,y_test,cv=cv)

array([0.72081909, 0.71814331, 0.72460683, 0.72117163, 0.71775742])

In [22]:
linear.coef_

array([-0.04746759, -0.08317375,  9.89534925, -4.69966274])

In [24]:
prediction = linear.predict(x_test)
prediction

array([ 4.62716726, 14.8460469 ,  9.18702407, ..., 28.38634177,
       28.85009994, 14.85780834])

In [26]:
from sklearn import metrics
print('MAE :'," ", metrics.mean_absolute_error(y_test,prediction))
print('MSE :'," ", metrics.mean_squared_error(y_test,prediction))
print('RMAE :'," ", np.sqrt(metrics.mean_squared_error(y_test,prediction)))

MAE :   3.7391156198007036
MSE :   21.808820654997945
RMAE :   4.66999150481004


In [32]:
a=[[5,6,0,4]]

In [33]:
linear.predict(a)

C:\Users\ashut\anaconda3\Conda\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([-0.11736623])

In [34]:
random.predict(a)

C:\Users\ashut\anaconda3\Conda\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([5.169673])

In [35]:
b=[[1 , 3, 2, 0]]

In [36]:
random.predict(b)

C:\Users\ashut\anaconda3\Conda\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([28.35367329])

In [59]:
import pickle
pickle.dump(random,open('random_model.pkl','wb'))


In [38]:
random.score

<bound method RegressorMixin.score of RandomForestRegressor(random_state=0)>

In [40]:
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}



In [41]:
from sklearn.model_selection import GridSearchCV

In [43]:
grid_search = GridSearchCV(random, param_grid, cv=5, scoring='neg_mean_squared_error', verbose=1, n_jobs=-1)
grid_search.fit(x_train, y_train)


Fitting 5 folds for each of 81 candidates, totalling 405 fits


KeyboardInterrupt: 

In [44]:
df3=pd.read_csv('data2.csv')

In [45]:
df3.head()

id     timestamp  hour  day  month  \
0  424553bb-7174-41ea-aeb4-fe06d4f4b9d7  1.544953e+09     9   16     12   
1  4bd23055-6827-41c6-b23b-3c491f24e74d  1.543284e+09     2   27     11   
2  4f9fee41-fde3-4767-bbf1-a00e108701fb  1.543818e+09     6    3     12   
3  9043bf77-1d45-4a93-9520-a083e0277f16  1.543594e+09    16   30     11   
4  357559cb-8c58-4278-a41a-e33b2e0997a3  1.544729e+09    19   13     12   

              datetime          timezone            source  \
0  2018-12-16 09:30:07  America/New_York  Haymarket Square   
1  2018-11-27 02:00:23  America/New_York  Haymarket Square   
2  2018-12-03 06:28:02  America/New_York          Back Bay   
3  2018-11-30 16:13:03  America/New_York          Back Bay   
4  2018-12-13 19:15:03  America/New_York         North End   

               destination cab_type  ... precipIntensityMax uvIndexTime  \
0            North Station     Lyft  ...             0.1276  1544979600   
1            North Station     Lyft  ...             0.1300  1543251600   
2  Northeastern University     Lyft  ...             0.0004  1543852800   
3  Northeastern University     Lyft  ...             0.0004  1543593600   
4                 West End     Uber  ...             0.0001  1544716800   

   temperatureMin  temperatureMinTime  temperatureMax  temperatureMaxTime  \
0           39.89          1545012000           43.68          1544968800   
1           40.49          1543233600           47.30          1543251600   
2           43.09          1543896000           57.02          1543852800   
3           28.64          1543579200           42.32          1543600800   
4           18.29          1544688000           33.83          1544731200   

   apparentTemperatureMin  apparentTemperatureMinTime  apparentTemperatureMax  \
0                   33.73                  1545012000                   38.07   
1                   36.20                  1543291200                   43.92   
2                   39.90                  1543896000                   56.35   
3                   29.29                  1543579200                   40.48   
4                   13.79                  1544688000                   32.85   

  apparentTemperatureMaxTime  
0                 1544958000  
1                 1543251600  
2                 1543852800  
3                 1543611600  
4                 1544734800  

[5 rows x 57 columns]

In [50]:
df3['name'].value_counts()

name
Black SUV    55096
Taxi         55095
UberX        55094
UberPool     55091
Lux          51235
Shared       51233
Name: count, dtype: int64

In [51]:
df['name'].value_counts()

name
0    55096
3    55095
5    55094
4    55091
1    51235
2    51233
Name: count, dtype: int64

In [52]:
df3['source'].value_counts()

source
Financial District         27385
Theatre District           26957
Back Bay                   26915
North End                  26908
Boston University          26908
Fenway                     26904
Northeastern University    26904
South Station              26900
Haymarket Square           26893
West End                   26824
Beacon Hill                26738
North Station              26608
Name: count, dtype: int64

In [53]:
df['source'].value_counts()

source
4     27385
10    26957
0     26915
6     26908
2     26908
3     26904
8     26904
9     26900
5     26893
11    26824
1     26738
7     26608
Name: count, dtype: int64

In [54]:
df3['destination'].value_counts()

destination
Financial District         27382
Theatre District           26947
Back Bay                   26910
Haymarket Square           26909
Boston University          26909
Fenway                     26904
North End                  26904
Northeastern University    26902
South Station              26899
West End                   26830
Beacon Hill                26738
North Station              26610
Name: count, dtype: int64

In [55]:
df['destination'].value_counts()

destination
4     27382
10    26947
0     26910
5     26909
2     26909
3     26904
6     26904
8     26902
9     26899
11    26830
1     26738
7     26610
Name: count, dtype: int64

In [56]:
df3['cab_type'].value_counts()

cab_type
Uber    220376
Lyft    102468
Name: count, dtype: int64

In [57]:
df['cab_type'].value_counts()

cab_type
1    220376
0    102468
Name: count, dtype: int64

In [60]:
import joblib


In [62]:
joblib.dump(random, 'random_model.pkl')


['random_model.pkl']

In [ ]:
df3